@hostname = http://localhost:3001

###
GET {{hostname}}/api/persons

###
GET {{hostname}}/info

###
GET {{hostname}}/api/persons/5

###
DELETE {{hostname}}/api/persons/2

###
POST {{hostname}}/api/persons
Content-Type: application/json

{
    "name": "Hawau",
    "number": "121-09-23456778"
}

###
POST {{hostname}}/api/persons
Content-Type: application/json

{
    "name": "Arto",
    "number": "040-123477"
}

###
POST {{hostname}}/api/persons
Content-Type: application/json

{
    "name": "John Lee",
    "number": "030-123456"
}

###
GET http://localhost:3001/api/persons